# header files
usr/include/opencv2/core.hpp
usr/include/opencv2/cvconfig.hpp
usr/include/opencv2/core/*
usr/include/opencv2/opencv.hpp
usr/include/opencv2/opencv_modules.hpp
usr/include/opencv/cv.h
usr/include/opencv/cv.hpp
usr/include/opencv/cxeigen.hpp
usr/include/opencv/cvaux.h
usr/include/opencv/cvaux.hpp
usr/include/opencv/cxcore.hpp
usr/include/opencv/cxmisc.h
# libraries
usr/lib/*/libopencv_core.so
